# Site settings
title: Honeypot Blog
email: team@honeypot.io
description: > # this means to ignore newlines until "baseurl:"
  Blog of awesome Honeypot
url: "http://blog.honeypot.io"
twitter_username: honeypotio
github_username:  honeypotio

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - _site/bin
  - vendor
  - bower.json
  - config.ru
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - Procfile
  - Rakefile
  - README.md

gems:
  - jekyll-paginate

# Blog Settings
paginate: 10

# Defaults for YAML Front Matter variables
defaults:
  -
    scope:
      path: ""
    values:
      excerpt_separator: <!--more-->
